In [1]:
from google.colab import drive  #mount google drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import json    #import json,csv,pandas and io 
import csv
import pandas as pd
import io
import matplotlib.pyplot as plt
import time
from datetime import datetime
import datetime
%matplotlib inline
import seaborn as sns
import plotly.express as px
import folium

In [3]:
from google.colab import files   # to import files in colab

**WMATA API TransitAnalysis**

In [ ]:
url ="https://api.wmata.com/Bus.svc/json/jBusPositions?RouteID=70"

import requests
import json

headers = {
     'content-type' : 'application/json',
     'api_key': 'ae979f0db7684af58ac62e684b994b02'
}

response = requests.get(url , headers=headers)

with open('data.json' ,'w') as outfile:
  json.dump(response.json() , outfile) 

with open('data.txt' ,'w') as outfile:
  json.dump(json.dumps(response.json(), indent =4 ,sort_keys =True) ,outfile)

print(json.dumps(response.json(), indent =4 ,sort_keys =True) ,outfile)

{
    "BusPositions": [
        {
            "BlockNumber": "M-721",
            "DateTime": "2022-11-27T00:58:38",
            "Deviation": 0.0,
            "DirectionNum": 1,
            "DirectionText": "SOUTH",
            "Lat": 38.88844472711737,
            "Lon": -77.02190399169922,
            "RouteID": "70",
            "TripEndTime": "2022-11-27T01:00:00",
            "TripHeadsign": "L'ENFANT PLAZA STATION",
            "TripID": "51242070",
            "TripStartTime": "2022-11-27T00:07:00",
            "VehicleID": "7233"
        },
        {
            "BlockNumber": "M-724",
            "DateTime": "2022-11-27T00:58:32",
            "Deviation": 6.0,
            "DirectionNum": 0,
            "DirectionText": "NORTH",
            "Lat": 38.96143301602068,
            "Lon": -77.02799172237002,
            "RouteID": "70",
            "TripEndTime": "2022-11-27T01:07:00",
            "TripHeadsign": "SILVER SPRING STATION",
            "TripID": "25306070",
            "TripStartTime": "2022-11-27T00:15:00",
            "VehicleID": "4534"
        },
        {
            "BlockNumber": "M-722",
            "DateTime": "2022-11-27T00:58:31",
            "Deviation": -5.0,
            "DirectionNum": 1,
            "DirectionText": "SOUTH",
            "Lat": 38.91925811767578,
            "Lon": -77.02189636230469,
            "RouteID": "70",
            "TripEndTime": "2022-11-27T01:20:00",
            "TripHeadsign": "L'ENFANT PLAZA STATION",
            "TripID": "47051070",
            "TripStartTime": "2022-11-27T00:27:00",
            "VehicleID": "4467"
        },
        {
            "BlockNumber": "M-726",
            "DateTime": "2022-11-27T00:58:27",
            "Deviation": 1.0,
            "DirectionNum": 0,
            "DirectionText": "NORTH",
            "Lat": 38.93106079101563,
            "Lon": -77.02352905273438,
            "RouteID": "70",
            "TripEndTime": "2022-11-27T01:27:00",
            "TripHeadsign": "SILVER SPRING STATION",
            "TripID": "10844070",
            "TripStartTime": "2022-11-27T00:35:00",
            "VehicleID": "4531"
        },
        {
            "BlockNumber": "M-725",
            "DateTime": "2022-11-27T00:58:36",
            "Deviation": 1.0,
            "DirectionNum": 1,
            "DirectionText": "SOUTH",
            "Lat": 38.96420729787726,
            "Lon": -77.02776416979339,
            "RouteID": "70",
            "TripEndTime": "2022-11-27T01:25:00",
            "TripHeadsign": "L'ENFANT PLAZA STATION",
            "TripID": "51798070",
            "TripStartTime": "2022-11-27T00:47:00",
            "VehicleID": "4539"
        },
        {
            "BlockNumber": "M-720",
            "DateTime": "2022-11-27T00:58:37",
            "Deviation": 5.0,
            "DirectionNum": 0,
            "DirectionText": "NORTH",
            "Lat": 38.9001637334409,
            "Lon": -77.02192588474439,
            "RouteID": "70",
            "TripEndTime": "2022-11-27T01:32:00",
            "TripHeadsign": "SILVER SPRING STATION",
            "TripID": "12392070",
            "TripStartTime": "2022-11-27T00:50:00",
            "VehicleID": "7218"
        },
        {
            "BlockNumber": "M-723",
            "DateTime": "2022-11-27T00:58:33",
            "Deviation": 0.0,
            "DirectionNum": 1,
            "DirectionText": "SOUTH",
            "Lat": 38.99341201782227,
            "Lon": -77.03011322021484,
            "RouteID": "70",
            "TripEndTime": "2022-11-27T01:45:00",
            "TripHeadsign": "L'ENFANT PLAZA STATION",
            "TripID": "36312070",
            "TripStartTime": "2022-11-27T01:07:00",
            "VehicleID": "7211"
        }
    ]
} <_io.TextIOWrapper name='data.txt' mode='w' encoding='UTF-8'>

In [ ]:
df = pd.read_json('data.json')  #read JSON file using pandas library

In [ ]:
df  #nested dataFrame

                                        BusPositions
0  {'VehicleID': '7233', 'Lat': 38.88844472711737...
1  {'VehicleID': '4534', 'Lat': 38.96143301602068...
2  {'VehicleID': '4467', 'Lat': 38.91925811767578...
3  {'VehicleID': '4531', 'Lat': 38.93106079101563...
4  {'VehicleID': '4539', 'Lat': 38.96420729787726...
5  {'VehicleID': '7218', 'Lat': 38.9001637334409,...
6  {'VehicleID': '7211', 'Lat': 38.99341201782227...

In [ ]:
df  #BusPositions dataframe
#NB: The dataframe is in a nested list in a single column Bus Positions

                                        BusPositions
0  {'VehicleID': '7233', 'Lat': 38.88844472711737...
1  {'VehicleID': '4534', 'Lat': 38.96143301602068...
2  {'VehicleID': '4467', 'Lat': 38.91925811767578...
3  {'VehicleID': '4531', 'Lat': 38.93106079101563...
4  {'VehicleID': '4539', 'Lat': 38.96420729787726...
5  {'VehicleID': '7218', 'Lat': 38.9001637334409,...
6  {'VehicleID': '7211', 'Lat': 38.99341201782227...

In [ ]:
df2=pd.concat([df.BusPositions.apply(pd.Series), df.drop('BusPositions', axis=1)], axis=1)  #Flatten nested attribute BusPositions in the dataFrame
df2  #rename the df with Flattened BusPositions to df2

,VehicleID,Lat,Lon,Deviation,DateTime,TripID,RouteID,DirectionNum,DirectionText,TripHeadsign,TripStartTime,TripEndTime,BlockNumber
0,7233,38.888445,-77.021904,0.0,2022-11-27T00:58:38,51242070,70,1,SOUTH,L'ENFANT PLAZA STATION,2022-11-27T00:07:00,2022-11-27T01:00:00,M-721
1,4534,38.961433,-77.027992,6.0,2022-11-27T00:58:32,25306070,70,0,NORTH,SILVER SPRING STATION,2022-11-27T00:15:00,2022-11-27T01:07:00,M-724
2,4467,38.919258,-77.021896,-5.0,2022-11-27T00:58:31,47051070,70,1,SOUTH,L'ENFANT PLAZA STATION,2022-11-27T00:27:00,2022-11-27T01:20:00,M-722
3,4531,38.931061,-77.023529,1.0,2022-11-27T00:58:27,10844070,70,0,NORTH,SILVER SPRING STATION,2022-11-27T00:35:00,2022-11-27T01:27:00,M-726
4,4539,38.964207,-77.027764,1.0,2022-11-27T00:58:36,51798070,70,1,SOUTH,L'ENFANT PLAZA STATION,2022-11-27T00:47:00,2022-11-27T01:25:00,M-725
5,7218,38.900164,-77.021926,5.0,2022-11-27T00:58:37,12392070,70,0,NORTH,SILVER SPRING STATION,2022-11-27T00:50:00,2022-11-27T01:32:00,M-720
6,7211,38.993412,-77.030113,0.0,2022-11-27T00:58:33,36312070,70,1,SOUTH,L'ENFANT PLAZA STATION,2022-11-27T01:07:00,2022-11-27T01:45:00,M-723

In [ ]:
df2.head (5) #dataframe head

,VehicleID,Lat,Lon,Deviation,DateTime,TripID,RouteID,DirectionNum,DirectionText,TripHeadsign,TripStartTime,TripEndTime,BlockNumber
0,7233,38.888445,-77.021904,0.0,2022-11-27T00:58:38,51242070,70,1,SOUTH,L'ENFANT PLAZA STATION,2022-11-27T00:07:00,2022-11-27T01:00:00,M-721
1,4534,38.961433,-77.027992,6.0,2022-11-27T00:58:32,25306070,70,0,NORTH,SILVER SPRING STATION,2022-11-27T00:15:00,2022-11-27T01:07:00,M-724
2,4467,38.919258,-77.021896,-5.0,2022-11-27T00:58:31,47051070,70,1,SOUTH,L'ENFANT PLAZA STATION,2022-11-27T00:27:00,2022-11-27T01:20:00,M-722
3,4531,38.931061,-77.023529,1.0,2022-11-27T00:58:27,10844070,70,0,NORTH,SILVER SPRING STATION,2022-11-27T00:35:00,2022-11-27T01:27:00,M-726
4,4539,38.964207,-77.027764,1.0,2022-11-27T00:58:36,51798070,70,1,SOUTH,L'ENFANT PLAZA STATION,2022-11-27T00:47:00,2022-11-27T01:25:00,M-725

In [ ]:
df2.describe() #Describing the dataframe

             Lat        Lon  Deviation  DirectionNum
count   7.000000   7.000000   7.000000      7.000000
mean   38.936854 -77.025018   1.142857      0.571429
std     0.037824   0.003502   3.625308      0.534522
min    38.888445 -77.030113  -5.000000      0.000000
25%    38.909711 -77.027878   0.000000      0.000000
50%    38.931061 -77.023529   1.000000      1.000000
75%    38.962820 -77.021915   3.000000      1.000000
max    38.993412 -77.021896   6.000000      1.000000

In [ ]:
df2.columns # MetroBus Columns/ Variables

Index(['VehicleID', 'Lat', 'Lon', 'Deviation', 'DateTime', 'TripID', 'RouteID',
       'DirectionNum', 'DirectionText', 'TripHeadsign', 'TripStartTime',
       'TripEndTime', 'BlockNumber'],
      dtype='object')

**Average time it takes for a Bus to complete a Route**

In [ ]:
df2['start'] = pd.to_datetime(df2[ 'TripStartTime'])   #Define start and stop between TripStartTime and TripEndTime 
df2['stop'] = pd.to_datetime(df2[ 'TripEndTime'])

In [ ]:
df2['delta'] = df2['stop'] - df2['start']  #Difference between start and stop

In [ ]:
df2['delta']  #Bustrips time differnce

0   0 days 00:53:00
1   0 days 00:52:00
2   0 days 00:53:00
3   0 days 00:52:00
4   0 days 00:38:00
5   0 days 00:42:00
6   0 days 00:38:00
Name: delta, dtype: timedelta64[ns]

In [ ]:
df2['delta'].sum()  #The sum of the bus trips

Timedelta('0 days 05:28:00')

In [ ]:
average_time = df2['delta'].sum() /7  #Average time it take for a Bus to complete a Route
print(average_time)

0 days 00:46:51.428571428

**Average time** it takes for a Bus to complete a route is **46 minutes and 51 seconds**

**Map Plot Visualization of BlockNumbers and Locations**

In [ ]:
df2 = df2[["Lat", "Lon", "BlockNumber"]]  #Mapping the locations and the BlockNumber

In [ ]:
map = folium.Map(location=[df2.Lat.mean(), df2.Lon.mean()], zoom_start=11, control_scale=True) 
#Creating the Map  using latitude and longitude coordinates

In [ ]:
for index, location_info in df2.iterrows():      #Adding the Transit Route  Points
    folium.Marker([location_info["Lat"], location_info["Lon"]], popup=location_info["BlockNumber"]).add_to(map)

In [ ]:
map  #plot the Transit map

***Estimate of the Speed of Bus ***

In [ ]:
pip install haversine  #install haversine to calculate distance between two points

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting haversine
  Downloading haversine-2.7.0-py2.py3-none-any.whl (6.9 kB)
Installing collected packages: haversine
Successfully installed haversine-2.7.0

In [ ]:
from haversine import inverse_haversine, Direction  #import haversine 
from math import pi

In [ ]:
from haversine import haversine  #Distance in miles between Bus Trip 1  to Bus Trip 2
haversine((38.888445,-77.021904 ),(38.961433,-77.027992 ), unit='mi')


=5.053597035114924 Miles

5.053597035114924

**Formula  = Speed = Distance /Time**

In [ ]:
Distance_of_Trip_One_to_Two = 5.053597035114924  #Distance in Miles
Hourly_Average_time_per_trip= 0.766666666666666718  #Time in 46:51.428571428 minutes

In [ ]:
Speed = Distance_of_Trip_One_to_Two / Hourly_Average_time_per_trip 
print(Speed)

6.591648306671639

**Speed = 6.59 ~ 6.6miles /hour**